// Copyright (C) 2026 Godynheil A. Quisto <godynheil@quisto.ph>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package app

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/godynheil/kk/internal/core"
	"github.com/godynheil/kk/internal/git"
)

func (a App) Init() error {
	if err := a.initKKDirs(); err != nil {
		return err
	}
	client := git.New(a.Root)
	if err := client.InitMain(); err != nil {
		return err
	}
	if err := syncProjectRegistry(a.Root); err != nil {
		return err
	}
	println("initialized kk repository")
	println("default branch: main")
	println("metadata: .kk/git")
	return nil
}

func (a App) initKKDirs() error {
	for _, dir := range []string{core.KKDir, core.KKGitDir, core.ObjectDir, core.TmpDir, core.LogDir} {
		if err := os.MkdirAll(filepath.Join(a.Root, dir), 0o750); err != nil {
			return err
		}
	}
	if !exists(filepath.Join(a.Root, core.RepoFile)) {
		info, err := core.NewRepoInfo(a.Root)
		if err != nil {
			return err
		}
		if err := core.WriteRepoInfo(a.Root, info); err != nil {
			return err
		}
	}
	if !exists(filepath.Join(a.Root, core.ConfigFile)) {
		if err := core.WriteConfig(a.Root, core.DefaultConfig()); err != nil {
			return err
		}
	}
	if !exists(filepath.Join(a.Root, core.TracksFile)) {
		if err := core.WriteTracks(a.Root, core.Tracks{Patterns: []string{}}); err != nil {
			return err
		}
	}
	if !exists(filepath.Join(a.Root, core.KKIgnoreFile)) {
		content := `# KK ignore file
# Generated by: kk init
# Remove or comment out any section that doesn't apply to your project.

# =========================================================
# OS-generated files
# =========================================================
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
Thumbs.db
ehthumbs.db
desktop.ini

# =========================================================
# IDEs & editors
# =========================================================

# JetBrains (Rider, GoLand, CLion, …)
.idea/

# Visual Studio / Visual Studio Code
.vs/
.vsconfig
.vscode/
*.suo
*.user
*.userosscache
*.sln.docstates

# Visual Studio solution & project files
# (Unity regenerates these automatically — safe to ignore)
*.sln
*.csproj
*.unityproj

# Misc editor swap / session files
*.swp
*.swo
*~

# =========================================================
# Unity
# =========================================================
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/
ExportedObj/
.consulo/

# Unity auto-generated debug symbols
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity crash / analytics artefacts
sysinfo.txt
crashlytics-build.properties

# =========================================================
# Unreal Engine
# =========================================================
Binaries/
Build/
DerivedDataCache/
Intermediate/
Saved/

*.VC.db
*.opensdf
*.opendb
*.sdf

# =========================================================
# Godot
# =========================================================
.godot/
.import/
export.cfg
export_presets.cfg
.mono/
data_*/

# =========================================================
# GameMaker
# =========================================================
# Compiled/cache artefacts — source *.yy files should be tracked
*.yyo
*.yyz

# =========================================================
# CryEngine / O3DE
# =========================================================
Cache/
BinTemp/

# =========================================================
# kk tool binaries (never track the tool itself)
# =========================================================
kk.exe
kk-portable.exe

# =========================================================
# General build output
# =========================================================
dist/
target/
node_modules/

# Mobile build artefacts
*.apk
*.aab
*.ipa

# =========================================================
# Temporary & log files
# =========================================================
*.tmp
*.temp
*.log
*.pid
*.seed
*.bak
`
		if err := os.WriteFile(filepath.Join(a.Root, core.KKIgnoreFile), []byte(content), 0o600); err != nil {
			return err
		}
	}
	return ensureGitExclude(a.Root)
}

func ensureGitExclude(root string) error {
	path := filepath.Join(root, core.KKGitDir, "info", "exclude")
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	data := ""
	if b, err := os.ReadFile(path); err == nil { // #nosec G304 -- path is the repository's .kk/git/info/exclude file.
		data = string(b)
	}
	for _, line := range strings.Split(data, "\n") {
		if strings.TrimSpace(line) == ".kk/" {
			return nil
		}
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600) // #nosec G304 -- path is the repository's .kk/git/info/exclude file.
	if err != nil {
		return err
	}
	defer func() {
		_ = f.Close()
	}()
	if data != "" && !strings.HasSuffix(data, "\n") {
		if _, err := f.WriteString("\n"); err != nil {
			return err
		}
	}
	_, err = f.WriteString(".kk/\n")
	return err
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
